### ISSUE TITLE
Cannot write to the registry key

### ISSUE THREAD

**Issue by sujithpaily** [aloopkin/WinCertes#2]
Got following error in windows server 2016. I run as Administrator

>WinCertes.exe -d domain.com

Unhandled Exception: System.UnauthorizedAccessException: Cannot write to the registry key.
   at System.ThrowHelper.ThrowUnauthorizedAccessException(ExceptionResource resource)
   at Microsoft.Win32.RegistryKey.EnsureWriteable()
   at Microsoft.Win32.RegistryKey.CreateSubKeyInternal(String subkey, RegistryKeyPermissionCheck permissionCheck, Object registrySecurityObj, RegistryOptions registryOptions)
   at Microsoft.Win32.RegistryKey.CreateSubKey(String subkey, RegistryKeyPermissionCheck permissionCheck)
   at Microsoft.Win32.RegistryKey.CreateSubKey(String subkey)
   at WinCertes.Config..ctor() in C:\Users\Alcide Loopkin\Documents\Visual Studio 2017\Projects\WinCertes\WinCertes\Config.cs:line 19
   at WinCertes.Program.Main(String[] args) in C:\Users\Alcide Loopkin\Documents\Visual Studio 2017\Projects\WinCertes\WinCertes\Program.cs:line 89

**To Reproduce**
WinCertes.exe -d domain.com

**Expected behavior**

**Screenshots or Logs**
If applicable, add screenshots or logs to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [ Windows Server]
 - Version [e.g. 2016]
 - IIS 10
- Administrator user

.

**Comment by sujithpaily** [comment]
I have changed path from C:\Programfiles (64) to c:\ProgramFiles and its working fine now
