### ISSUE TITLE
IIS required but I using Apache24

### ISSUE THREAD

**Issue by metacreo** [aloopkin/WinCertes#47]
Win server 2008 R2 sp1 no iis, apache24 used
'2023-07-13 14:31:54.7629|INFO|Generated orders and validated challenges for domains: www.com
2023-07-13 14:32:00.4725|INFO|Retrieved certificate from the CA. The certificate is in C:\ProgramData\WinCertes\CertsTmp\67f268ac-8aa1-4420-96c2-20f643b9146c.pfx
2023-07-13 14:32:00.5817|INFO|Stored certificate with DN CN=www.com into Windows Personal Local Machine store
2023-07-13 14:32:00.6441|ERROR|Could not bind certificate to site www.com: Retrieving the COM class factory for component with CLSID {2B72133B-3F5B-4602-8952-803546CE3344} failed due to the following error: 80040154 Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)).
System.Runtime.InteropServices.COMException (0x80040154): Retrieving the COM class factory for component with CLSID {2B72133B-3F5B-4602-8952-803546CE3344} failed due to the following error: 80040154 Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)).
   at System.Runtime.Remoting.RemotingServices.AllocateUninitializedObject(RuntimeType objectType)
   at System.Runtime.Remoting.Activation.ActivationServices.CreateInstance(RuntimeType serverType)
   at System.Runtime.Remoting.Activation.ActivationServices.IsCurrentContextOK(RuntimeType serverType, Object[] props, Boolean bNewObj)
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance[T]()
   at Microsoft.Web.Administration.ConfigurationManager.CreateAdminManager[TClass,TInterface](WebConfigurationMap webConfigMap, Boolean isAdminConfig)
   at Microsoft.Web.Administration.ConfigurationManager.CreateConfiguration(WebConfigurationMap configMap, String configPathToEdit, Boolean isAdminConfig)
   at Microsoft.Web.Administration.ConfigurationManager.GetConfiguration(String rawConfigurationPath, String cacheKey, Boolean isAdminConfig)
   at Microsoft.Web.Administration.ServerManager.get_SitesSection()
   at Microsoft.Web.Administration.ServerManager.get_Sites()
   at WinCertes.Utils.BindCertificateForIISSite(X509Certificate2 certificate, String siteName, Int32 port)
2023-07-13 14:32:00.7065|INFO|Removed files from filesystem: C:\ProgramData\WinCertes\CertsTmp\67f268ac-8aa1-4420-96c2-20f643b9146c.pfx, C:\ProgramData\WinCertes\CertsTmp\67f268ac-8aa1-4420-96c2-20f643b9146c.cer, C:\ProgramData\WinCertes\CertsTmp\67f268ac-8aa1-4420-96c2-20f643b9146c.key'

**Comment by hqiasjehrlb** [comment]
Facing the same problem, and I use the `--scriptfile=...` argument to run script for copy certificate files ([ref](https://github.com/aloopkin/WinCertes#about-powershell-scripting)).

But finally I got an error:
```
Could not execute ...: Cannot load Windows PowerShell snap-in Microsoft.PowerShell.Diagnostics because of the following error: Could not load file or assembly 'Microsoft.PowerShell.Commands' or one of its dependencies.
```

Anyone can help?
